project:
  output-dir: ../html

lang: zh
#subtitle: "æ•™æè¡¥å……è§£é‡Šä¸è¯´æ˜"
title-slide-attributes:
    data-background-image: https://assets.qiufei.site/zwu/nice_to_meet_you.png
    data-background-size: contain
    data-background-opacity: "0.5"
author: "é‚±é£"


format:
  revealjs:
    width: 1280
    height: 720
    slide-level: 3
    slide-number: true
    show-slide-number: all
    fig-align: center
    #smaller: true
    theme: serif
    logo: zwu_logo.png
    embed-resources: true
    footer: "é‚±é£ ğŸ’Œ qiufei@zwu.edu.cn"
    scrollable: true
    css: my.css


execute: 
  eval: true
  echo: true
  warning: false 