lang: zh
subtitle: "æ•™æè¡¥å……è§£é‡Šä¸è¯´æ˜"
title-slide-attributes:
    data-background-image: world_cn.png
    data-background-size: contain
    data-background-opacity: "0.5"
author: "é‚±é£"

format:
  revealjs:
    slide-level: 3
    slide-number: true
    show-slide-number: all
    fig-align: center
    #smaller: true
    theme: serif
    logo: zwu_logo.png
    embed-resources: true
    footer: "é‚±é£ ğŸ’Œ hfutqiufei@163.com"
    scrollable: true
    css: my.css


execute: 
  eval: true
  echo: false
  warning: false 